version: "3.8"
services:  
  db_wex:
    container_name: db_wex
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: purchase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/initdb-postgres.sql:/docker-entrypoint-initdb.d/initdb-postgres.sql
    networks:
      - wex-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "purchase",
          "-U",
          "postgres"
        ]
      timeout: 20s
      interval: 2s
      retries: 10

networks:
  wex-network:
    name: wex-network
    driver: bridge

volumes:
  postgres:
    driver: local